import{a as q,S as P,i as n}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="https://pixabay.com/api/",B="55066757-aef92cd57a3265a375d263145";async function f(o,t){return(await q.get(M,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:i,comments:w,downloads:S})=>`
        <li class="gallery-item">
          <a href="${a}">
            <img src="${s}" alt="${e}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${i}</p>
            <p><b>Comments:</b> ${w}</p>
            <p><b>Downloads:</b> ${S}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){m.innerHTML=""}function p(){y.classList.add("is-visible")}function b(){y.classList.remove("is-visible")}function L(){h.classList.add("is-visible")}function d(){h.classList.remove("is-visible")}const O=document.querySelector(".form"),A=document.querySelector(".load-more");let l="",c=1,u=0;const v=15;O.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements.searchQuery.value.trim(),!!l){c=1,$(),d(),p();try{const t=await f(l,c);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query."});return}u=t.totalHits,g(t.hits),Math.ceil(u/v)>1?L():(d(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong!"})}finally{b()}}});A.addEventListener("click",async()=>{c+=1,d(),p();try{const o=await f(l,c);g(o.hits);const t=Math.ceil(u/v);c>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):L();const s=document.querySelector(".gallery-item");if(s){const a=s.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}catch{n.error({message:"Error loading more images!"})}finally{b()}});
//# sourceMappingURL=index.js.map
